import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Dock from "./components/Dock";
import NavBar from "./components/NavBar";
import ScannerProvider from "./Context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScannerProvider>
          <div>
            <NavBar />
          </div>
          {children}
          <div style={{ position: "fixed", bottom: 0, left: 0, right: 0 }}>
            <Dock />
          </div>
        </ScannerProvider>
        {/* <div>
          Building
          <NavBar />
        </div>
        <div>
          <Dock />
        </div> */}
      </body>
    </html>
  );
}
